# .github/FUNDING.yml

open_collective: s4ft
ko_fi: s4ft
buy_me_a_coffee: s4ft
custom: [
  "https://buy.stripe.com/4gM5kE16MfCb4b72C60sU00",
  "https://buy.stripe.com/fZu7sMg1G3Tt7nj4Ke0sU01",
  "https://pix.doacoes.s4ft.fun",
  "https://s4ft.fun/doar"
]
